"Compiled on a Linux 2.6.32 system on 2012-04-27.\n"
"Available extensions:\n"
"	crypt add-on version 2.1 by Michael Glad and others\n"
"	Native POSIX Threads Library by Ulrich Drepper et al\n"
"	BIND-8.2.3-T5B\n"
